import { int, object, string, type infer as ZodInfer } from 'zod';
import { BODY_PAYLOAD_MUST_BE_OBJECT } from '../Shared/Shared.messages.js';
import {
	PRODUCT_DESCRIPTION_MUST_BE_STRING,
	PRODUCT_DESCRIPTION_MUST_HAVE_MAX_LENGTH,
	PRODUCT_DESCRIPTION_MUST_HAVE_MIN_LENGTH,
	PRODUCT_NAME_MUST_BE_STRING,
	PRODUCT_NAME_MUST_HAVE_MAX_LENGTH,
	PRODUCT_NAME_MUST_HAVE_MIN_LENGTH,
	PRODUCT_PRICE_MUST_BE_INTEGER,
	PRODUCT_PRICE_MUST_BE_POSITIVE,
} from './Product.messages.js';

const PRODUCT_DESCRIPTION_MAX_LENGTH = 500;
const PRODUCT_DESCRIPTION_MIN_LENGTH = 10;

const PRODUCT_NAME_MAX_LENGTH = 50;
const PRODUCT_NAME_MIN_LENGTH = 5;

export const ProductCreateSchema = object(
	{
		description: string(PRODUCT_DESCRIPTION_MUST_BE_STRING)
			.min(
				PRODUCT_DESCRIPTION_MIN_LENGTH,
				PRODUCT_DESCRIPTION_MUST_HAVE_MIN_LENGTH(PRODUCT_DESCRIPTION_MIN_LENGTH),
			)
			.max(
				PRODUCT_DESCRIPTION_MAX_LENGTH,
				PRODUCT_DESCRIPTION_MUST_HAVE_MAX_LENGTH(PRODUCT_DESCRIPTION_MAX_LENGTH),
			),
		name: string(PRODUCT_NAME_MUST_BE_STRING)
			.min(
				PRODUCT_NAME_MIN_LENGTH,
				PRODUCT_NAME_MUST_HAVE_MIN_LENGTH(PRODUCT_NAME_MIN_LENGTH),
			)
			.max(
				PRODUCT_NAME_MAX_LENGTH,
				PRODUCT_NAME_MUST_HAVE_MAX_LENGTH(PRODUCT_NAME_MAX_LENGTH),
			),
		price: int(PRODUCT_PRICE_MUST_BE_INTEGER).positive(PRODUCT_PRICE_MUST_BE_POSITIVE),
	},
	BODY_PAYLOAD_MUST_BE_OBJECT,
);

export type ProductCreateDto = ZodInfer<typeof ProductCreateSchema>;
