// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma-next/adapter-mongo/codec-types';
import type { Vector } from '@prisma-next/adapter-mongo/codec-types';

import type { MongoContractWithTypeMaps, MongoTypeMaps } from '@prisma-next/mongo-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:48c0e548b92d2e420a6efb5a50949eefd4377e5d45df38b4037f6e257b83c719'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:840de65fba7eb950a31487f74ee420b9c21205f38bce58579026747e0264e840'>;

export type CodecTypes = MongoCodecTypes;
export type OperationTypes = Record<string, never>;

export type FieldOutputTypes = {
  readonly Account: {
    readonly createdAt: CodecTypes['mongo/date@1']['output'];
    readonly email: CodecTypes['mongo/string@1']['output'];
    readonly id: CodecTypes['mongo/string@1']['output'];
    readonly password: CodecTypes['mongo/string@1']['output'];
    readonly updatedAt: CodecTypes['mongo/date@1']['output'];
  };
  readonly PendingAccountVerification: {
    readonly createdAt: CodecTypes['mongo/date@1']['output'];
    readonly email: CodecTypes['mongo/string@1']['output'];
    readonly expiresIn: CodecTypes['mongo/date@1']['output'];
    readonly otp: CodecTypes['mongo/string@1']['output'];
    readonly password: CodecTypes['mongo/string@1']['output'];
    readonly updatedAt: CodecTypes['mongo/date@1']['output'];
  };
  readonly Product: {
    readonly createdAt: CodecTypes['mongo/date@1']['output'];
    readonly details: CodecTypes['mongo/string@1']['output'];
    readonly expiresAt: CodecTypes['mongo/date@1']['output'];
    readonly id: CodecTypes['mongo/string@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly price: CodecTypes['mongo/int32@1']['output'];
    readonly updatedAt: CodecTypes['mongo/date@1']['output'];
  };
  readonly User: {
    readonly accountId: CodecTypes['mongo/string@1']['output'];
    readonly createdAt: CodecTypes['mongo/date@1']['output'];
    readonly credits: CodecTypes['mongo/int32@1']['output'];
    readonly isTeacher: CodecTypes['mongo/bool@1']['output'];
    readonly role: CodecTypes['mongo/string@1']['output'];
    readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly username: CodecTypes['mongo/string@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly Account: {
    readonly createdAt: CodecTypes['mongo/date@1']['input'];
    readonly email: CodecTypes['mongo/string@1']['input'];
    readonly id: CodecTypes['mongo/string@1']['input'];
    readonly password: CodecTypes['mongo/string@1']['input'];
    readonly updatedAt: CodecTypes['mongo/date@1']['input'];
  };
  readonly PendingAccountVerification: {
    readonly createdAt: CodecTypes['mongo/date@1']['input'];
    readonly email: CodecTypes['mongo/string@1']['input'];
    readonly expiresIn: CodecTypes['mongo/date@1']['input'];
    readonly otp: CodecTypes['mongo/string@1']['input'];
    readonly password: CodecTypes['mongo/string@1']['input'];
    readonly updatedAt: CodecTypes['mongo/date@1']['input'];
  };
  readonly Product: {
    readonly createdAt: CodecTypes['mongo/date@1']['input'];
    readonly details: CodecTypes['mongo/string@1']['input'];
    readonly expiresAt: CodecTypes['mongo/date@1']['input'];
    readonly id: CodecTypes['mongo/string@1']['input'];
    readonly name: CodecTypes['mongo/string@1']['input'];
    readonly price: CodecTypes['mongo/int32@1']['input'];
    readonly updatedAt: CodecTypes['mongo/date@1']['input'];
  };
  readonly User: {
    readonly accountId: CodecTypes['mongo/string@1']['input'];
    readonly createdAt: CodecTypes['mongo/date@1']['input'];
    readonly credits: CodecTypes['mongo/int32@1']['input'];
    readonly isTeacher: CodecTypes['mongo/bool@1']['input'];
    readonly role: CodecTypes['mongo/string@1']['input'];
    readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    readonly username: CodecTypes['mongo/string@1']['input'];
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, OperationTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = ContractType<
  {
    readonly collections: {
      readonly accounts: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [{ readonly field: 'id'; readonly direction: 1 }];
            readonly unique: true;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly createdAt: { readonly bsonType: 'date' };
              readonly email: { readonly bsonType: 'string' };
              readonly id: { readonly bsonType: 'string' };
              readonly password: { readonly bsonType: 'string' };
              readonly updatedAt: { readonly bsonType: 'date' };
            };
            readonly required: readonly ['createdAt', 'email', 'id', 'password', 'updatedAt'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly pendingAccountVerification: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [{ readonly field: 'otp'; readonly direction: 1 }];
            readonly unique: true;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly createdAt: { readonly bsonType: 'date' };
              readonly email: { readonly bsonType: 'string' };
              readonly expiresIn: { readonly bsonType: 'date' };
              readonly otp: { readonly bsonType: 'string' };
              readonly password: { readonly bsonType: 'string' };
              readonly updatedAt: { readonly bsonType: 'date' };
            };
            readonly required: readonly [
              'createdAt',
              'email',
              'expiresIn',
              'otp',
              'password',
              'updatedAt',
            ];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly products: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [{ readonly field: 'id'; readonly direction: 1 }];
            readonly unique: true;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly createdAt: { readonly bsonType: 'date' };
              readonly details: { readonly bsonType: 'string' };
              readonly expiresAt: { readonly bsonType: 'date' };
              readonly id: { readonly bsonType: 'string' };
              readonly name: { readonly bsonType: 'string' };
              readonly price: { readonly bsonType: 'int' };
              readonly updatedAt: { readonly bsonType: 'date' };
            };
            readonly required: readonly [
              'createdAt',
              'details',
              'expiresAt',
              'id',
              'name',
              'price',
              'updatedAt',
            ];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly users: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [{ readonly field: 'accountId'; readonly direction: 1 }];
            readonly unique: true;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly accountId: { readonly bsonType: 'string' };
              readonly createdAt: { readonly bsonType: 'date' };
              readonly credits: { readonly bsonType: 'int' };
              readonly isTeacher: { readonly bsonType: 'bool' };
              readonly role: { readonly bsonType: 'string' };
              readonly updatedAt: { readonly bsonType: 'date' };
              readonly username: { readonly bsonType: 'string' };
            };
            readonly required: readonly [
              'accountId',
              'createdAt',
              'credits',
              'isTeacher',
              'role',
              'updatedAt',
              'username',
            ];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly Account: {
      readonly fields: {
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly password: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: '1:1';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['accountId'];
          };
        };
      };
      readonly storage: { readonly collection: 'accounts' };
    };
    readonly PendingAccountVerification: {
      readonly fields: {
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly expiresIn: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
        readonly otp: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly password: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'pendingAccountVerification' };
    };
    readonly Product: {
      readonly fields: {
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
        readonly details: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly expiresAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'products' };
    };
    readonly User: {
      readonly fields: {
        readonly accountId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
        readonly credits: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly isTeacher: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
        };
        readonly role: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
        readonly username: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: {
        readonly account: {
          readonly to: 'Account';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['accountId'];
            readonly targetFields: readonly ['id'];
          };
        };
      };
      readonly storage: { readonly collection: 'users' };
    };
  }
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly accounts: 'Account';
    readonly pendingAccountVerification: 'PendingAccountVerification';
    readonly products: 'Product';
    readonly users: 'User';
  };
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
